import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import { PROJECT_ROOT, listTemplates } from "./aiscientist.ts"

function readIf(p: string): string | null {
  try {
    return readFileSync(p, "utf8")
  } catch {
    return null
  }
}

function section(title: string, lines: string[]): string {
  return `## ${title}\n\n${lines.map((l) => `- ${l}`).join("\n")}\n`
}

export function generateAgentsMd(root: string = PROJECT_ROOT): { path: string; content: string; files: number } {
  const lines: string[] = []

  const pkg = readIf(join(root, "opencode-tui", "package.json"))
  if (pkg) {
    try {
      const j = JSON.parse(pkg) as { scripts?: Record<string, string> }
      const scripts = Object.entries(j.scripts ?? []).map(([k, v]) => `\`${k}\`: ${v}`)
      if (scripts.length) lines.push(`TUI build/test commands (opencode-tui/): ${scripts.join(", ")}`)
    } catch {}
  }
  const reqs = readIf(join(root, "requirements.txt"))
  if (reqs) {
    const deps = reqs.split("\n").map((l) => l.trim()).filter((l) => l && !l.startsWith("#")).slice(0, 12)
    lines.push(`Python deps (requirements.txt): ${deps.join(", ")}${deps.length >= 12 ? " …" : ""}`)
  }
  const pyproject = readIf(join(root, "pyproject.toml"))
  if (pyproject) {
    const name = pyproject.match(/^name\s*=\s*"([^"]+)"/m)?.[1]
    if (name) lines.push(`Python package: \`${name}\` (pyproject.toml; \`pip install -e .\` gives the \`aiscientist\` command)`)
  }
  if (existsSync(join(root, "run_tests.sh"))) lines.push("Test runner: `bash run_tests.sh` (pytest over `tests/`)")

  const rootDirs = readdirSync(root, { withFileTypes: true })
    .filter((e) => e.isDirectory() && !e.name.startsWith(".") && e.name !== "node_modules" && e.name !== "__pycache__")
    .map((e) => e.name)
  lines.push(`Top-level dirs: ${rootDirs.join(", ")}`)

  const templates = listTemplates()
  if (templates.length) lines.push(`Research templates (${templates.length}): ${templates.slice(0, 12).join(", ")}${templates.length > 12 ? " …" : ""}`)
  if (existsSync(join(root, "example_papers"))) lines.push("`example_papers/` — reference papers the scientist loop reviews")

  const env = readIf(join(root, ".env"))
  const envKeys = env ? env.split("\n").map((l) => l.match(/^([A-Z_][A-Z0-9_]*)=/)?.[1]).filter((x): x is string => !!x) : []
  if (envKeys.length) lines.push(`Config: .env provides ${envKeys.join(", ")} (never commit secrets)`)

  const content =
    `# AGENTS.md\n\n` +
    `Project context for the AI-Scientist main agent. Generated by /init at ${new Date().toISOString()}.\n\n` +
    section("What this is", [
      "AI-Scientist: an autonomous research pipeline (ideas → novelty → experiments → writeup → review).",
      "The primary interface is the TUI in `opencode-tui/` (bun + OpenTUI): Dashboard, Chat, Explorer, Notes, Agents, Article.",
    ]) +
    section("Commands", lines) +
    section("Conventions", [
      "Job state lives in `results/jobs.jsonl`; events in `results/events/<job>.jsonl` — edit only via the tools.",
      "Pipeline stages emit events; the TUI tails them (no polling loops in the UI thread).",
    ])

  const path = join(root, "AGENTS.md")
  writeFileSync(path, content)
  return { path, content, files: rootDirs.length }
}
